-- =========================
-- SQL Agenda e Agendamentos
-- =========================
-- Executar após criar-tabelas.sql (depende de SAAS_Usuarios, SAAS_Conexões, SAAS_Contatos e da função is_owner).
-- Cria tabelas de agenda, trigger de conflito de slot, função de horários livres e RLS.

-- =========================
-- 1) TABELAS
-- =========================

-- AGENDA CONFIG (múltiplas por usuário)
CREATE TABLE IF NOT EXISTS public."SAAS_Agenda_Config" (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  "userId"              UUID NOT NULL,
  nome                  TEXT NOT NULL,
  "horaInicio"          TIME,
  "horaFim"             TIME,
  "diasAtendimento"     SMALLINT[],
  "duracaoMinutos"      INTEGER,
  "horasAntesConfirmacao" INTEGER,
  "idConexao"           BIGINT,
  "templateConfirmacao" TEXT,
  CONSTRAINT "SAAS_Agenda_Config_userId_fkey" FOREIGN KEY ("userId") REFERENCES public."SAAS_Usuarios"(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "SAAS_Agenda_Config_idConexao_fkey" FOREIGN KEY ("idConexao") REFERENCES public."SAAS_Conexões"(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- AGENDAMENTOS (atendimento — ocupam slot na agenda)
CREATE TABLE IF NOT EXISTS public."SAAS_Agendamentos" (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  "userId"              UUID NOT NULL,
  "idAgendaConfig"      BIGINT NOT NULL,
  "idConexao"           BIGINT,
  "idContato"           BIGINT,
  telefone              TEXT,
  "dataHora"            TIMESTAMPTZ NOT NULL,
  "duracaoMinutos"      INTEGER,
  status                TEXT NOT NULL DEFAULT 'agendado',
  "confirmacaoEnviada"  BOOLEAN NOT NULL DEFAULT false,
  observacoes           TEXT,
  CONSTRAINT "SAAS_Agendamentos_userId_fkey" FOREIGN KEY ("userId") REFERENCES public."SAAS_Usuarios"(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "SAAS_Agendamentos_idAgendaConfig_fkey" FOREIGN KEY ("idAgendaConfig") REFERENCES public."SAAS_Agenda_Config"(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "SAAS_Agendamentos_idConexao_fkey" FOREIGN KEY ("idConexao") REFERENCES public."SAAS_Conexões"(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "SAAS_Agendamentos_idContato_fkey" FOREIGN KEY ("idContato") REFERENCES public."SAAS_Contatos"(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- AGENDAMENTOS MENSAGENS (não ocupa agenda)
CREATE TABLE IF NOT EXISTS public."SAAS_Agendamentos_Mensagens" (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  "userId"        UUID NOT NULL,
  "idConexao"     BIGINT,
  "idContato"     BIGINT,
  telefone        TEXT,
  mensagem        TEXT,
  "dataHora"      TIMESTAMPTZ NOT NULL,
  status          TEXT NOT NULL DEFAULT 'pendente',
  "enviadoEm"     TIMESTAMPTZ,
  CONSTRAINT "SAAS_Agendamentos_Mensagens_userId_fkey" FOREIGN KEY ("userId") REFERENCES public."SAAS_Usuarios"(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "SAAS_Agendamentos_Mensagens_idConexao_fkey" FOREIGN KEY ("idConexao") REFERENCES public."SAAS_Conexões"(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "SAAS_Agendamentos_Mensagens_idContato_fkey" FOREIGN KEY ("idContato") REFERENCES public."SAAS_Contatos"(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- =========================
-- 2) ÍNDICES
-- =========================

CREATE INDEX IF NOT EXISTS idx_agenda_config_userId
  ON public."SAAS_Agenda_Config"("userId");

CREATE INDEX IF NOT EXISTS idx_agendamentos_userId
  ON public."SAAS_Agendamentos"("userId");

CREATE INDEX IF NOT EXISTS idx_agendamentos_idContato
  ON public."SAAS_Agendamentos"("idContato");

CREATE INDEX IF NOT EXISTS idx_agendamentos_idAgendaConfig
  ON public."SAAS_Agendamentos"("idAgendaConfig");

CREATE INDEX IF NOT EXISTS idx_agendamentos_dataHora
  ON public."SAAS_Agendamentos"("dataHora");

CREATE INDEX IF NOT EXISTS idx_agendamentos_confirmacao
  ON public."SAAS_Agendamentos"("confirmacaoEnviada", "dataHora");

CREATE INDEX IF NOT EXISTS idx_agendamentos_mensagens_userId
  ON public."SAAS_Agendamentos_Mensagens"("userId");

CREATE INDEX IF NOT EXISTS idx_agendamentos_mensagens_idContato
  ON public."SAAS_Agendamentos_Mensagens"("idContato");

CREATE INDEX IF NOT EXISTS idx_agendamentos_mensagens_dataHora
  ON public."SAAS_Agendamentos_Mensagens"("dataHora");

CREATE INDEX IF NOT EXISTS idx_agendamentos_mensagens_status
  ON public."SAAS_Agendamentos_Mensagens"(status) WHERE status = 'pendente';

-- =========================
-- 3) TRIGGER conflito de slot
-- =========================

CREATE OR REPLACE FUNCTION public.trg_agendamentos_check_slot_overlap()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_duracao INTEGER;
  v_inicio TIMESTAMPTZ;
  v_fim TIMESTAMPTZ;
  v_count INTEGER;
BEGIN
  v_duracao := COALESCE(NEW."duracaoMinutos",
    (SELECT "duracaoMinutos" FROM public."SAAS_Agenda_Config" WHERE id = NEW."idAgendaConfig" LIMIT 1),
    30);
  v_inicio := NEW."dataHora";
  v_fim := NEW."dataHora" + (v_duracao || ' minutes')::INTERVAL;

  SELECT COUNT(*) INTO v_count
  FROM public."SAAS_Agendamentos" a
  WHERE a."idAgendaConfig" = NEW."idAgendaConfig"
    AND a.id IS DISTINCT FROM COALESCE(NEW.id, 0)
    AND a.status IN ('agendado', 'confirmado', 'realizado', 'nao_compareceu')
    AND (
      (a."dataHora", a."dataHora" + COALESCE(a."duracaoMinutos",
        (SELECT "duracaoMinutos" FROM public."SAAS_Agenda_Config" WHERE id = a."idAgendaConfig" LIMIT 1),
        30) * INTERVAL '1 minute') OVERLAPS (v_inicio, v_fim)
    );

  IF v_count > 0 THEN
    RAISE EXCEPTION 'Horário já ocupado nesta agenda. Escolha outro slot.';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_agendamentos_check_slot ON public."SAAS_Agendamentos";
CREATE TRIGGER trg_agendamentos_check_slot
  BEFORE INSERT OR UPDATE ON public."SAAS_Agendamentos"
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_agendamentos_check_slot_overlap();

-- =========================
-- 4) FUNÇÃO horários livres (7 dias)
-- =========================

CREATE OR REPLACE FUNCTION public.f_horarios_livres_agenda(
  p_id_agenda BIGINT,
  p_data_inicio DATE DEFAULT NULL
)
RETURNS TABLE (
  data_hora_inicio TIMESTAMPTZ,
  data_hora_fim TIMESTAMPTZ
)
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_cfg RECORD;
  v_dia DATE;
  v_data_inicio DATE;
  v_data_fim DATE;
  v_slot_ini TIMESTAMP;
  v_slot_fim TIMESTAMP;
  v_slot_ini_ts TIMESTAMPTZ;
  v_slot_fim_ts TIMESTAMPTZ;
  v_dow SMALLINT;
  v_tem_overlap BOOLEAN;
BEGIN
  v_data_inicio := COALESCE(p_data_inicio, CURRENT_DATE);
  v_data_fim := v_data_inicio + 6;

  SELECT ac."horaInicio", ac."horaFim", ac."diasAtendimento", ac."duracaoMinutos"
  INTO v_cfg
  FROM public."SAAS_Agenda_Config" ac
  WHERE ac.id = p_id_agenda
  LIMIT 1;

  IF NOT FOUND OR v_cfg."horaInicio" IS NULL OR v_cfg."horaFim" IS NULL OR v_cfg."diasAtendimento" IS NULL OR v_cfg."duracaoMinutos" IS NULL THEN
    RETURN;
  END IF;

  FOR v_dia IN
    SELECT generate_series(v_data_inicio, v_data_fim, '1 day'::interval)::date
  LOOP
    v_dow := EXTRACT(DOW FROM v_dia)::SMALLINT;
    IF NOT (v_dow = ANY(v_cfg."diasAtendimento")) THEN
      CONTINUE;
    END IF;

    v_slot_ini := (v_dia::timestamp + v_cfg."horaInicio");
    WHILE (v_dia::timestamp + v_cfg."horaFim") > (v_slot_ini + (v_cfg."duracaoMinutos" || ' minutes')::interval) LOOP
      v_slot_fim := v_slot_ini + (v_cfg."duracaoMinutos" || ' minutes')::interval;
      v_slot_ini_ts := v_slot_ini AT TIME ZONE 'America/Sao_Paulo';
      v_slot_fim_ts := v_slot_fim AT TIME ZONE 'America/Sao_Paulo';

      SELECT EXISTS (
        SELECT 1
        FROM public."SAAS_Agendamentos" a
        WHERE a."idAgendaConfig" = p_id_agenda
          AND a.status IN ('agendado', 'confirmado', 'realizado', 'nao_compareceu')
          AND (
            (a."dataHora", a."dataHora" + COALESCE(a."duracaoMinutos", v_cfg."duracaoMinutos") * INTERVAL '1 minute')
            OVERLAPS (v_slot_ini_ts, v_slot_fim_ts)
          )
      ) INTO v_tem_overlap;

      IF NOT v_tem_overlap THEN
        data_hora_inicio := v_slot_ini_ts;
        data_hora_fim := v_slot_fim_ts;
        RETURN NEXT;
      END IF;

      v_slot_ini := v_slot_fim;
    END LOOP;
  END LOOP;
END;
$$;

-- =========================
-- 5) RLS
-- =========================

ALTER TABLE public."SAAS_Agenda_Config" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SAAS_Agendamentos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SAAS_Agendamentos_Mensagens" ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF to_regclass('public."SAAS_Agenda_Config"') IS NOT NULL THEN
    DROP POLICY IF EXISTS "service_role_full_access" ON public."SAAS_Agenda_Config";
    CREATE POLICY "service_role_full_access" ON public."SAAS_Agenda_Config" TO service_role USING (true) WITH CHECK (true);
    DROP POLICY IF EXISTS "usuario_crud_agenda_config" ON public."SAAS_Agenda_Config";
    CREATE POLICY "usuario_crud_agenda_config"
      ON public."SAAS_Agenda_Config"
      FOR ALL
      TO authenticated
      USING (public.is_owner("userId"))
      WITH CHECK (public.is_owner("userId"));
    GRANT SELECT, INSERT, UPDATE, DELETE ON public."SAAS_Agenda_Config" TO authenticated;
  END IF;
END$$;

DO $$
BEGIN
  IF to_regclass('public."SAAS_Agendamentos"') IS NOT NULL THEN
    DROP POLICY IF EXISTS "service_role_full_access" ON public."SAAS_Agendamentos";
    CREATE POLICY "service_role_full_access" ON public."SAAS_Agendamentos" TO service_role USING (true) WITH CHECK (true);
    DROP POLICY IF EXISTS "usuario_crud_agendamentos" ON public."SAAS_Agendamentos";
    CREATE POLICY "usuario_crud_agendamentos"
      ON public."SAAS_Agendamentos"
      FOR ALL
      TO authenticated
      USING (public.is_owner("userId"))
      WITH CHECK (public.is_owner("userId"));
    GRANT SELECT, INSERT, UPDATE, DELETE ON public."SAAS_Agendamentos" TO authenticated;
  END IF;
END$$;

DO $$
BEGIN
  IF to_regclass('public."SAAS_Agendamentos_Mensagens"') IS NOT NULL THEN
    DROP POLICY IF EXISTS "service_role_full_access" ON public."SAAS_Agendamentos_Mensagens";
    CREATE POLICY "service_role_full_access" ON public."SAAS_Agendamentos_Mensagens" TO service_role USING (true) WITH CHECK (true);
    DROP POLICY IF EXISTS "usuario_crud_agendamentos_mensagens" ON public."SAAS_Agendamentos_Mensagens";
    CREATE POLICY "usuario_crud_agendamentos_mensagens"
      ON public."SAAS_Agendamentos_Mensagens"
      FOR ALL
      TO authenticated
      USING (public.is_owner("userId"))
      WITH CHECK (public.is_owner("userId"));
    GRANT SELECT, INSERT, UPDATE, DELETE ON public."SAAS_Agendamentos_Mensagens" TO authenticated;
  END IF;
END$$;

